name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress node comamand line
        default: node runner.js        
jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4.1.1

      - name: Install depedencies
        run: npm install

      - name: Run E2E tests
        run: ${{github.event.inputs.cli }}

        
      
      
    
